// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/articles.ts";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/api/pdf.ts";
import * as $4 from "./routes/articles/[articleId].tsx";
import * as $5 from "./routes/docs/[docId].tsx";
import * as $6 from "./routes/index.tsx";
import * as $$0 from "./islands/Article.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/PdfDoc.tsx";
import * as $$3 from "./islands/PdfDocCanvas.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/articles.ts": $1,
    "./routes/api/joke.ts": $2,
    "./routes/api/pdf.ts": $3,
    "./routes/articles/[articleId].tsx": $4,
    "./routes/docs/[docId].tsx": $5,
    "./routes/index.tsx": $6,
  },
  islands: {
    "./islands/Article.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/PdfDoc.tsx": $$2,
    "./islands/PdfDocCanvas.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
