// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/articles.ts";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/api/pdf.ts";
import * as $4 from "./routes/articles/[articleId].tsx";
import * as $5 from "./routes/docs/[docId].tsx";
import * as $6 from "./routes/docs/htext/[docId].tsx";
import * as $7 from "./routes/docs/json/[docId].tsx";
import * as $8 from "./routes/docs/text/[docId].tsx";
import * as $9 from "./routes/index.tsx";
import * as $$0 from "./islands/Article.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/HTextDoc.tsx";
import * as $$3 from "./islands/JsonDoc.tsx";
import * as $$4 from "./islands/PdfDoc.tsx";
import * as $$5 from "./islands/PdfDocCanvas.tsx";
import * as $$6 from "./islands/RecentArticles.tsx";
import * as $$7 from "./islands/TextDoc.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/articles.ts": $1,
    "./routes/api/joke.ts": $2,
    "./routes/api/pdf.ts": $3,
    "./routes/articles/[articleId].tsx": $4,
    "./routes/docs/[docId].tsx": $5,
    "./routes/docs/htext/[docId].tsx": $6,
    "./routes/docs/json/[docId].tsx": $7,
    "./routes/docs/text/[docId].tsx": $8,
    "./routes/index.tsx": $9,
  },
  islands: {
    "./islands/Article.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/HTextDoc.tsx": $$2,
    "./islands/JsonDoc.tsx": $$3,
    "./islands/PdfDoc.tsx": $$4,
    "./islands/PdfDocCanvas.tsx": $$5,
    "./islands/RecentArticles.tsx": $$6,
    "./islands/TextDoc.tsx": $$7,
  },
  baseUrl: import.meta.url,
};

export default manifest;
